/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
  // Ultra-minimal core plugins for maximum speed
  corePlugins: {
    // Essential layout
    display: true,
    flexDirection: true,
    flexWrap: true,
    justifyContent: true,
    alignItems: true,
    gap: true,
    
    // Essential spacing
    margin: true,
    padding: true,
    width: true,
    height: true,
    maxWidth: true,
    maxHeight: true,
    
    // Essential typography
    fontSize: true,
    fontWeight: true,
    lineHeight: true,
    textAlign: true,
    textColor: true,
    
    // Essential styling
    backgroundColor: true,
    borderWidth: true,
    borderColor: true,
    borderRadius: true,
    opacity: true,
    
    // Essential positioning
    position: true,
    inset: true,
    zIndex: true,
    
    // Essential utilities
    overflow: true,
    boxSizing: true,
    cursor: true,
    
    // Disable everything else
    preflight: true,
    container: false,
    accessibility: false,
    appearance: false,
    backgroundAttachment: false,
    backgroundClip: false,
    backgroundImage: false,
    backgroundOpacity: false,
    backgroundPosition: false,
    backgroundRepeat: false,
    backgroundSize: false,
    borderCollapse: false,
    borderSpacing: false,
    boxDecorationBreak: false,
    caretColor: false,
    clear: false,
    divideColor: false,
    divideOpacity: false,
    divideStyle: false,
    divideWidth: false,
    fill: false,
    flex: false,
    flexGrow: false,
    flexShrink: false,
    float: false,
    fontFamily: false,
    fontSmoothing: false,
    fontStyle: false,
    fontVariantNumeric: false,
    gradientColorStops: false,
    gridAutoColumns: false,
    gridAutoFlow: false,
    gridAutoRows: false,
    gridColumn: false,
    gridColumnEnd: false,
    gridColumnStart: false,
    gridRow: false,
    gridRowEnd: false,
    gridRowStart: false,
    gridTemplateColumns: false,
    gridTemplateRows: false,
    isolation: false,
    justifyItems: false,
    justifySelf: false,
    letterSpacing: false,
    listStylePosition: false,
    listStyleType: false,
    minHeight: false,
    minWidth: false,
    mixBlendMode: false,
    objectFit: false,
    objectPosition: false,
    order: false,
    outline: false,
    overscrollBehavior: false,
    placeContent: false,
    placeItems: false,
    placeSelf: false,
    placeholderColor: false,
    placeholderOpacity: false,
    pointerEvents: false,
    resize: false,
    ringColor: false,
    ringOffsetColor: false,
    ringOffsetWidth: false,
    ringOpacity: false,
    ringWidth: false,
    rotate: false,
    scale: false,
    skew: false,
    space: false,
    stroke: false,
    strokeWidth: false,
    tableLayout: false,
    textDecoration: false,
    textDecorationColor: false,
    textDecorationStyle: false,
    textDecorationThickness: false,
    textIndent: false,
    textOpacity: false,
    textOverflow: false,
    textTransform: false,
    textUnderlineOffset: false,
    transform: false,
    transformOrigin: false,
    transitionDelay: false,
    transitionDuration: false,
    transitionProperty: false,
    transitionTimingFunction: false,
    translate: false,
    userSelect: false,
    verticalAlign: false,
    visibility: false,
    whitespace: false,
    wordBreak: false,
  },
}; 