[package]
name = "geomi_mascot_voting"
version = "1.0.0"

[addresses]
geomi_mascot_voting = "_"

[dev-addresses]
geomi_mascot_voting = "0x42"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "aptos-node-v1.8.0" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib", rev = "aptos-node-v1.8.0" }

[dev-dependencies] 